frr defaults traditional
service integrated-vtysh-config
!
hostname server1
!
router ospf
 router-id 2.2.2.2
 passive-interface lo
 network 172.20.0.0/16 area 0
 network 172.21.0.0/16 area 0
!
line vty
!
