services:
  client1:
    build:
      context: .
    networks:
      net1:
        ipv4_address: 172.20.0.2
      net4:
        ipv4_address: 172.23.0.2
    volumes:
      - ./shared/common:/shared/common
      - ./shared/client1_data:/shared/unique

  server1:
    build:
      context: .
    networks:
      net1:
        ipv4_address: 172.20.0.3
      net2:
        ipv4_address: 172.21.0.3
    volumes:
        - ./shared/common:/shared/common
        - ./shared/server1_data:/shared/unique

  server2:
    build:
      context: .
    networks:
      net2:
        ipv4_address: 172.21.0.4
      net3:
        ipv4_address: 172.22.0.4
    volumes:
      - ./shared/common:/shared/common
      - ./shared/server2_data:/shared/unique

  client2:
    build:
      context: .
    networks:
      net3:
        ipv4_address: 172.22.0.5
      net4:
        ipv4_address: 172.23.0.5
    volumes:
      - ./shared/common:/shared/common
      - ./shared/client2_data:/shared/unique

networks:
  net1:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  net2:
    ipam:
      config:
        - subnet: 172.21.0.0/16
  net3:
    ipam:
      config:
        - subnet: 172.22.0.0/16
  net4:
    ipam:
      config:
        - subnet: 172.23.0.0/16
